server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springbooter
    username: root
    password: password
  liquibase:
    changeLogFile: liquibase/changelog-prod.xml
    dropFirst: false
