# https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springbooter
    username: root
    password: password
  liquibase:
    changeLogFile: liquibase/changelog-dev.xml
    dropFirst: true  #ignored due to liquibase bug - therefore 00-clear.sql exists as workaround

  main:
    banner-mode: 'off'

application:
  accessControlAllowOrigin: '*'
  network:
    readTimeoutInSeconds: 60
    connectionTimeoutInSeconds: 60

management:
  endpoints:
    web:
      exposure:
        include: 'mappings'
