# https://circleci.com/docs/2.0/language-java/

version: 2.1
jobs:
  build:
    docker:
      # check for new versions: https://circleci.com/docs/2.0/circleci-images/#openjdk
      - image: circleci/openjdk:11.0.3-jdk-stretch

      - image: circleci/mariadb:10.4.6-bionic
        environment:
          MYSQL_DATABASE: springbooter_test
          MYSQL_USER: root
          MYSQL_PASSWORD: password

    steps:
      - checkout

      - restore_cache:
          key: circleci-spring-booter-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-spring-booter-{{ checksum "pom.xml" }}

      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run: mvn clean package # run the actual tests
